# Generated by Django 4.2.7 on 2023-11-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appForm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productos",
            name="totalDevuelto",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productos",
            name="totalFacturado",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usuario",
            name="tipoUsuario",
            field=models.CharField(default="default_value", max_length=50),
        ),
        migrations.AlterField(
            model_name="productos",
            name="codigo",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productos",
            name="lote",
            field=models.IntegerField(default=0),
        ),
    ]
